Server:
  RunMode: debug
  HTTPPost: 3000
  ReadTimeout: 60
  WriteTimeout: 60
Socket: 
  Active: false
  Url: /ws
App:
  LogSavePath: storage/log
  LogFileName: app
  LogFileExt: .log
  LogLevel: debug
JWT:
  Secret: chandaye666
  Issuer: 陈大爷
  Expire: 720000000
  Salt: yanyanyan
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: treasure
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis: 
  Host: 127.0.0.1:6379
  Password: ""
  DBNumber: 15